---
- hosts: localhost
  connection: local
  vars:
    - config: "{{ lookup('file', '/config/config.json') | from_json }}"
  tasks:
    - name: Build resource list
      command: buildResourceList.py
      register: inputList
      changed_when: False
    
    - name: Parse resource list
      set_fact:
        resourceList: "{{ inputList.stdout | from_json }}"
    
    - name: Configure S3 Buckets
      s3_bucket:
        aws_access_key: "{{ config.aws.aws_access_key }}"
        aws_secret_key: "{{ config.aws.aws_secret_key }}"
        name: "{{ item }}"
        region: "{{ resourceList.s3[item].region }}"
        state: "{{ resourceList.s3[item].state }}"
        force: yes
      with_items:
        "{{ resourceList.s3 | default([]) }}"

    - name: Configure DynamoDB Tables
      dynamodb_table:
        aws_access_key: "{{ config.aws.aws_access_key }}"
        aws_secret_key: "{{ config.aws.aws_secret_key }}"
        name: "{{ item }}"
        region: "{{ resourceList.dynamodb[item].region }}"
        hash_key_name: "{{ resourceList.dynamodb[item].hash_key_name }}"
        read_capacity: "{{ resourceList.dynamodb[item].read_capacity | default(5) }}"
        write_capacity: "{{ resourceList.dynamodb[item].write_capacity | default(5) }}"
        state: "{{ resourceList.dynamodb[item].state }}"
      with_items:
        "{{ resourceList.dynamodb | default([]) }}"
